// Import next components
import type { Metadata } from 'next'

// Import styles
import './globals.css'
import '@radix-ui/themes/styles.css'

// Import third party components
import { Theme } from '@radix-ui/themes'

// Import components
import Navigation from '@/components/Navigation'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<Theme>
					<Navigation />

					<main>
						{children}
					</main>
				</Theme>
			</body>
		</html>
	)
}
